// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDysun8q6pma3mnCi388mss2CdN2Kp2AUE',
    appId: '1:1083574367083:web:e157b63473262ffee5122e',
    messagingSenderId: '1083574367083',
    projectId: 'chat-app-3ded9',
    authDomain: 'chat-app-3ded9.firebaseapp.com',
    storageBucket: 'chat-app-3ded9.appspot.com',
    measurementId: 'G-7KWYPF9YVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw7l1mRr2BrZF547Wro--u4xpwkgktfZI',
    appId: '1:1083574367083:android:8a5085f70a2b3e12e5122e',
    messagingSenderId: '1083574367083',
    projectId: 'chat-app-3ded9',
    storageBucket: 'chat-app-3ded9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUMxIcCAHCVIK0jYLuzCtizvZkUm5wsSc',
    appId: '1:1083574367083:ios:796715fac65d4415e5122e',
    messagingSenderId: '1083574367083',
    projectId: 'chat-app-3ded9',
    storageBucket: 'chat-app-3ded9.appspot.com',
    iosClientId: '1083574367083-iehhac9j1aqutubds76on63in8f0o6cd.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUMxIcCAHCVIK0jYLuzCtizvZkUm5wsSc',
    appId: '1:1083574367083:ios:f9043bb090ab42d4e5122e',
    messagingSenderId: '1083574367083',
    projectId: 'chat-app-3ded9',
    storageBucket: 'chat-app-3ded9.appspot.com',
    iosClientId: '1083574367083-hfcb2ms104hfptkfcu7emo81prd9q1do.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
